version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686 # Jaeger UI
      - 4317:55680  # GRPC OTLP
      - 13133:13133 # Healthcheck   
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile-keycloak-with-opentelemetry
    ports:
      - 8080:8080
      - 9464:9464
    environment:
      JAVA_OPTS: "-javaagent:/tmp/opentelemetry-javaagent-all.jar -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true"
      OTEL_SERVICE_NAME: keycloak
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    depends_on:
      - jaeger
