version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686   
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile-keycloak-with-opentelemetry
    ports:
      - 8080:8080
      - 9464:9464
    environment:
      JAVA_OPTS_APPEND: "-javaagent:/tmp/opentelemetry-javaagent-all.jar"
      OTEL_SERVICE_NAME: keycloak
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_METRICS_EXPORTER: prometheus
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - jaeger
